---
abstract: 'Simple configuration scripting to deploy CouchDB databases'
author:
  - 'Robin Berjon, <robin @t berjon d.t com>'
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CouchDB-Deploy
no_index:
  directory:
    - inc
    - t
requires:
  CouchDB::Client: 0
  Data::Compare: 0
  File::Spec: 0
  Sub::Exporter: 0
  perl: 5.6.0
version: 0.02
